[package]
name = "future_starter"
version = "0.1.0"
authors = ["Adam Wright <shaladdle@gmail.com>"]

[dependencies]
clap = "2.2"
tarpc = { path = "../../" }
tarpc-plugins = { path = "../../src/plugins/" }
tokio-core = "0.1.3"
futures = "0.1.7"
