[package]
name = "sync_starter"
version = "0.1.0"
authors = ["Adam Wright <shaladdle@gmail.com>"]

[dependencies]
clap = "2.2"
tarpc = { path = "../../" }
tarpc-plugins = { path = "../../src/plugins/" }
